### ISSUE TITLE
严重：支付回调判断逻辑错误

### ISSUE THREAD

**Issue by CoWorkForHappy** [jeequan/jeepay#17]
问题：在NotifyPayServiceImpl.java 文件的method 
@Override
    public Map doWxPayNotify(String jsonParam)中的
byte payStatus = payOrder.getStatus(); // 
            if (payStatus != PayConstant.PAY_STATUS_SUCCESS && payStatus != PayConstant.PAY_STATUS_COMPLETE) {.............................................................}
payOrder.getStatus() 获得的值未被初始化为零，会导致支付失败。

**Comment by 1ibo** [comment]
这里是微信支付回调的处理，为什么payOrder.getStatus() 获得的值要被初始化为零？
